# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawKnowledgeClient, RawKnowledgeClient
from .types.create_knowledge_response import CreateKnowledgeResponse
from .types.delete_knowledge_response import DeleteKnowledgeResponse
from .types.get_knowledge_response import GetKnowledgeResponse
from .types.knowledge_create_request_content_type import KnowledgeCreateRequestContentType
from .types.list_knowledge_response import ListKnowledgeResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class KnowledgeClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawKnowledgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawKnowledgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawKnowledgeClient
        """
        return self._raw_client

    def list_knowledge(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListKnowledgeResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKnowledgeResponse
            Danh sách knowledge

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.knowledge.list_knowledge()
        """
        _response = self._raw_client.list_knowledge(request_options=request_options)
        return _response.data

    def create_knowledge(
        self,
        *,
        title: str,
        content: str,
        idempotency_key: typing.Optional[str] = None,
        content_type: typing.Optional[KnowledgeCreateRequestContentType] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateKnowledgeResponse:
        """
        Parameters
        ----------
        title : str

        content : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        content_type : typing.Optional[KnowledgeCreateRequestContentType]

        tags : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateKnowledgeResponse
            Knowledge đã tạo

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.knowledge.create_knowledge(
            title="title",
            content="content",
        )
        """
        _response = self._raw_client.create_knowledge(
            title=title,
            content=content,
            idempotency_key=idempotency_key,
            content_type=content_type,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    def get_knowledge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetKnowledgeResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetKnowledgeResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.knowledge.get_knowledge(
            id="id",
        )
        """
        _response = self._raw_client.get_knowledge(id, request_options=request_options)
        return _response.data

    def delete_knowledge(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteKnowledgeResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteKnowledgeResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.knowledge.delete_knowledge(
            id="id",
        )
        """
        _response = self._raw_client.delete_knowledge(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data


class AsyncKnowledgeClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawKnowledgeClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawKnowledgeClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawKnowledgeClient
        """
        return self._raw_client

    async def list_knowledge(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListKnowledgeResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListKnowledgeResponse
            Danh sách knowledge

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.list_knowledge()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_knowledge(request_options=request_options)
        return _response.data

    async def create_knowledge(
        self,
        *,
        title: str,
        content: str,
        idempotency_key: typing.Optional[str] = None,
        content_type: typing.Optional[KnowledgeCreateRequestContentType] = OMIT,
        tags: typing.Optional[typing.Sequence[str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateKnowledgeResponse:
        """
        Parameters
        ----------
        title : str

        content : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        content_type : typing.Optional[KnowledgeCreateRequestContentType]

        tags : typing.Optional[typing.Sequence[str]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateKnowledgeResponse
            Knowledge đã tạo

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.create_knowledge(
                title="title",
                content="content",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_knowledge(
            title=title,
            content=content,
            idempotency_key=idempotency_key,
            content_type=content_type,
            tags=tags,
            request_options=request_options,
        )
        return _response.data

    async def get_knowledge(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetKnowledgeResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetKnowledgeResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.get_knowledge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_knowledge(id, request_options=request_options)
        return _response.data

    async def delete_knowledge(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteKnowledgeResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteKnowledgeResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.knowledge.delete_knowledge(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_knowledge(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data
