# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .agent import Agent
    from .agent_status import AgentStatus
    from .api_key import ApiKey
    from .api_key_create_response import ApiKeyCreateResponse
    from .channel_config import ChannelConfig
    from .channel_config_type import ChannelConfigType
    from .chat_completion import ChatCompletion
    from .chat_completion_usage import ChatCompletionUsage
    from .chat_message import ChatMessage
    from .chat_message_role import ChatMessageRole
    from .envelope import Envelope
    from .envelope_status import EnvelopeStatus
    from .knowledge import Knowledge
    from .knowledge_content_type import KnowledgeContentType
    from .knowledge_detail import KnowledgeDetail
    from .mcp_server import McpServer
    from .mcp_server_tool import McpServerTool
    from .mcp_server_tool_auth_type import McpServerToolAuthType
    from .mcp_server_tool_kind import McpServerToolKind
    from .model import Model
    from .model_list import ModelList
    from .ok_response import OkResponse
    from .organization import Organization
    from .organization_member import OrganizationMember
    from .organization_member_role import OrganizationMemberRole
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".agent",
    "AgentStatus": ".agent_status",
    "ApiKey": ".api_key",
    "ApiKeyCreateResponse": ".api_key_create_response",
    "ChannelConfig": ".channel_config",
    "ChannelConfigType": ".channel_config_type",
    "ChatCompletion": ".chat_completion",
    "ChatCompletionUsage": ".chat_completion_usage",
    "ChatMessage": ".chat_message",
    "ChatMessageRole": ".chat_message_role",
    "Envelope": ".envelope",
    "EnvelopeStatus": ".envelope_status",
    "Knowledge": ".knowledge",
    "KnowledgeContentType": ".knowledge_content_type",
    "KnowledgeDetail": ".knowledge_detail",
    "McpServer": ".mcp_server",
    "McpServerTool": ".mcp_server_tool",
    "McpServerToolAuthType": ".mcp_server_tool_auth_type",
    "McpServerToolKind": ".mcp_server_tool_kind",
    "Model": ".model",
    "ModelList": ".model_list",
    "OkResponse": ".ok_response",
    "Organization": ".organization",
    "OrganizationMember": ".organization_member",
    "OrganizationMemberRole": ".organization_member_role",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentStatus",
    "ApiKey",
    "ApiKeyCreateResponse",
    "ChannelConfig",
    "ChannelConfigType",
    "ChatCompletion",
    "ChatCompletionUsage",
    "ChatMessage",
    "ChatMessageRole",
    "Envelope",
    "EnvelopeStatus",
    "Knowledge",
    "KnowledgeContentType",
    "KnowledgeDetail",
    "McpServer",
    "McpServerTool",
    "McpServerToolAuthType",
    "McpServerToolKind",
    "Model",
    "ModelList",
    "OkResponse",
    "Organization",
    "OrganizationMember",
    "OrganizationMemberRole",
]
