# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .agent_status import AgentStatus


class Agent(UniversalBaseModel):
    id: str
    display_name: str
    status: AgentStatus
    llm_provider: typing.Optional[str] = None
    llm_model: typing.Optional[str] = None
    llm_base_url: typing.Optional[str] = None
    knowledge_ids: typing.Optional[typing.List[str]] = None
    enabled_tools: typing.Optional[typing.List[str]] = None
    mcp_dynamic_server_ids: typing.Optional[typing.List[str]] = None
    mcp_dynamic_tool_filter: typing.Optional[typing.Dict[str, typing.Any]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
