# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .bad_request_error_body_code import BadRequestErrorBodyCode
from .bad_request_error_body_status import BadRequestErrorBodyStatus


class BadRequestErrorBody(UniversalBaseModel):
    status: typing.Optional[BadRequestErrorBodyStatus] = None
    code: typing.Optional[BadRequestErrorBodyCode] = None
    message: str
    data: typing.Optional[typing.Any] = None
    trace_id: str
    timestamp: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
