# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .camera_vendor import CameraVendor


class Camera(UniversalBaseModel):
    """
    Camera IP/RTSP thuộc organization. `rtsp_password` KHÔNG được trả về
    (redact) — chỉ có `has_rtsp_password`. `vendor_config` là JSON tùy hãng
    (channel/stream, device_serial, ...).
    """

    id: str
    display_name: str
    vendor: CameraVendor
    vendor_label: typing.Optional[str] = None
    rtsp_url: typing.Optional[str] = None
    rtsp_username: typing.Optional[str] = None
    has_rtsp_password: typing.Optional[bool] = None
    vendor_config: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    JSON cấu hình tùy hãng (channel, stream, ...)
    """

    enabled: typing.Optional[bool] = None
    notes: typing.Optional[str] = None
    created_at: typing.Optional[dt.datetime] = None
    updated_at: typing.Optional[dt.datetime] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
