# This file was auto-generated by Fern from our API Definition.

import typing

ChannelConfigType = typing.Union[
    typing.Literal[
        "telegram",
        "discord",
        "slack",
        "google_chat",
        "whatsapp",
        "signal",
        "sms",
        "email",
        "homeassistant",
        "mattermost",
        "matrix",
        "dingtalk",
        "feishu",
        "wecom",
        "wecom_callback",
        "weixin",
        "bluebubbles",
        "qq",
        "yuanbao",
        "teams",
        "line",
        "webhook",
        "msgraph_webhook",
    ],
    typing.Any,
]
