# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class McpToolDefinition(UniversalBaseModel):
    """
    Ràng buộc bảo mật / kích thước cho REST tool.
    """

    max_timeout_ms: typing.Optional[int] = None
    max_response_kb: typing.Optional[int] = None
    schema_validate: typing.Optional[bool] = None
    allowed_hosts: typing.Optional[typing.List[str]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
