# This file was auto-generated by Fern from our API Definition.

import typing

McpEndpointMongoOp = typing.Union[
    typing.Literal["find", "findOne", "aggregate", "insertOne", "updateOne", "deleteOne"], typing.Any
]
