# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .mcp_endpoint_mongo_op import McpEndpointMongoOp
from .mcp_endpoint_param import McpEndpointParam


class McpEndpoint(UniversalBaseModel):
    method: typing.Optional[str] = pydantic.Field(default=None)
    """
    GET | POST | PUT | PATCH | DELETE (REST)
    """

    path: typing.Optional[str] = None
    name: typing.Optional[str] = None
    description: typing.Optional[str] = None
    params: typing.Optional[typing.List[McpEndpointParam]] = None
    body_schema: typing.Optional[str] = None
    sql_template: typing.Optional[str] = None
    mongo_op: typing.Optional[McpEndpointMongoOp] = None
    collection: typing.Optional[str] = None
    filter_json: typing.Optional[str] = None
    pipeline_json: typing.Optional[str] = None
    redis_command: typing.Optional[str] = None
    redis_args: typing.Optional[str] = pydantic.Field(default=None)
    """
    JSON array template, e.g. ["user:{id}"]
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
