# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class McpAuthConfig(UniversalBaseModel):
    """
    Thông tin xác thực / kết nối DB. Khi tạo tool có thể gửi secret (token, password, dsn).
    Response list/get chỉ trả field đã redact (không phơi token/password/dsn).
    """

    token: typing.Optional[str] = None
    header_name: typing.Optional[str] = None
    username: typing.Optional[str] = None
    password: typing.Optional[str] = None
    driver: typing.Optional[str] = None
    dsn: typing.Optional[str] = None
    read_only: typing.Optional[bool] = None
    max_rows: typing.Optional[int] = None
    engine: typing.Optional[str] = None
    host: typing.Optional[str] = None
    port: typing.Optional[int] = None
    database: typing.Optional[str] = None
    ssl_mode: typing.Optional[str] = None
    extra_params: typing.Optional[str] = None
    raw_dsn: typing.Optional[str] = None
    auth_source: typing.Optional[str] = None
    tls: typing.Optional[bool] = None
    db_index: typing.Optional[int] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
