# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .mcp_endpoint_param_in import McpEndpointParamIn
from .mcp_endpoint_param_type import McpEndpointParamType


class McpEndpointParam(UniversalBaseModel):
    name: typing.Optional[str] = None
    type: typing.Optional[McpEndpointParamType] = None
    in_: typing_extensions.Annotated[
        typing.Optional[McpEndpointParamIn], FieldMetadata(alias="in"), pydantic.Field(alias="in")
    ] = None
    required: typing.Optional[bool] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
