# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .not_found_error_body_code import NotFoundErrorBodyCode
from .not_found_error_body_status import NotFoundErrorBodyStatus


class NotFoundErrorBody(UniversalBaseModel):
    status: typing.Optional[NotFoundErrorBodyStatus] = None
    code: typing.Optional[NotFoundErrorBodyCode] = None
    message: str
    data: typing.Optional[typing.Any] = None
    trace_id: str
    timestamp: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
