# This file was auto-generated by Fern from our API Definition.

import typing

NotFoundErrorBodyCode = typing.Union[
    typing.Literal[
        "unauthorized",
        "forbidden",
        "not_found",
        "invalid_request",
        "rate_limited",
        "payload_too_large",
        "service_unavailable",
        "internal",
    ],
    typing.Any,
]
