# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .too_many_requests_error_body_code import TooManyRequestsErrorBodyCode
from .too_many_requests_error_body_status import TooManyRequestsErrorBodyStatus


class TooManyRequestsErrorBody(UniversalBaseModel):
    status: typing.Optional[TooManyRequestsErrorBodyStatus] = None
    code: typing.Optional[TooManyRequestsErrorBodyCode] = None
    message: str
    data: typing.Optional[typing.Any] = None
    trace_id: str
    timestamp: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
