# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.mcp_auth_config import McpAuthConfig
from ..types.mcp_endpoint import McpEndpoint
from ..types.mcp_tool_definition import McpToolDefinition
from .raw_client import AsyncRawMcpServersClient, RawMcpServersClient
from .types.create_mcp_server_response import CreateMcpServerResponse
from .types.create_mcp_server_tool_response import CreateMcpServerToolResponse
from .types.list_mcp_server_tools_response import ListMcpServerToolsResponse
from .types.list_mcp_servers_response import ListMcpServersResponse
from .types.mcp_server_tool_create_request_auth_type import McpServerToolCreateRequestAuthType
from .types.mcp_server_tool_create_request_kind import McpServerToolCreateRequestKind

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class McpServersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMcpServersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMcpServersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMcpServersClient
        """
        return self._raw_client

    def list_mcp_servers(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListMcpServersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServersResponse
            Danh sách MCP server

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.list_mcp_servers()
        """
        _response = self._raw_client.list_mcp_servers(request_options=request_options)
        return _response.data

    def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerResponse:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerResponse
            MCP server đã tạo

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.create_mcp_server(
            name="name",
        )
        """
        _response = self._raw_client.create_mcp_server(
            name=name, idempotency_key=idempotency_key, description=description, request_options=request_options
        )
        return _response.data

    def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServerToolsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServerToolsResponse
            Danh sách tool

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.list_mcp_server_tools(
            id="id",
        )
        """
        _response = self._raw_client.list_mcp_server_tools(id, request_options=request_options)
        return _response.data

    def create_mcp_server_tool(
        self,
        id: str,
        *,
        kind: McpServerToolCreateRequestKind,
        slug: str,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        rest_resource_path: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolCreateRequestAuthType] = OMIT,
        auth_config: typing.Optional[McpAuthConfig] = OMIT,
        endpoints: typing.Optional[typing.Sequence[McpEndpoint]] = OMIT,
        definition: typing.Optional[McpToolDefinition] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerToolResponse:
        """
        Parameters
        ----------
        id : str

        kind : McpServerToolCreateRequestKind

        slug : str

        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        rest_resource_path : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolCreateRequestAuthType]

        auth_config : typing.Optional[McpAuthConfig]

        endpoints : typing.Optional[typing.Sequence[McpEndpoint]]

        definition : typing.Optional[McpToolDefinition]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerToolResponse
            Tool đã tạo

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.create_mcp_server_tool(
            id="id",
            kind="rest",
            slug="slug",
            display_name="display_name",
        )
        """
        _response = self._raw_client.create_mcp_server_tool(
            id,
            kind=kind,
            slug=slug,
            display_name=display_name,
            idempotency_key=idempotency_key,
            description=description,
            base_url=base_url,
            rest_resource_path=rest_resource_path,
            auth_type=auth_type,
            auth_config=auth_config,
            endpoints=endpoints,
            definition=definition,
            sort_order=sort_order,
            is_active=is_active,
            request_options=request_options,
        )
        return _response.data


class AsyncMcpServersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMcpServersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMcpServersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMcpServersClient
        """
        return self._raw_client

    async def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServersResponse
            Danh sách MCP server

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.list_mcp_servers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_mcp_servers(request_options=request_options)
        return _response.data

    async def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerResponse:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerResponse
            MCP server đã tạo

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.create_mcp_server(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_mcp_server(
            name=name, idempotency_key=idempotency_key, description=description, request_options=request_options
        )
        return _response.data

    async def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServerToolsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServerToolsResponse
            Danh sách tool

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.list_mcp_server_tools(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_mcp_server_tools(id, request_options=request_options)
        return _response.data

    async def create_mcp_server_tool(
        self,
        id: str,
        *,
        kind: McpServerToolCreateRequestKind,
        slug: str,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        rest_resource_path: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolCreateRequestAuthType] = OMIT,
        auth_config: typing.Optional[McpAuthConfig] = OMIT,
        endpoints: typing.Optional[typing.Sequence[McpEndpoint]] = OMIT,
        definition: typing.Optional[McpToolDefinition] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerToolResponse:
        """
        Parameters
        ----------
        id : str

        kind : McpServerToolCreateRequestKind

        slug : str

        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        rest_resource_path : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolCreateRequestAuthType]

        auth_config : typing.Optional[McpAuthConfig]

        endpoints : typing.Optional[typing.Sequence[McpEndpoint]]

        definition : typing.Optional[McpToolDefinition]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerToolResponse
            Tool đã tạo

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.create_mcp_server_tool(
                id="id",
                kind="rest",
                slug="slug",
                display_name="display_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_mcp_server_tool(
            id,
            kind=kind,
            slug=slug,
            display_name=display_name,
            idempotency_key=idempotency_key,
            description=description,
            base_url=base_url,
            rest_resource_path=rest_resource_path,
            auth_type=auth_type,
            auth_config=auth_config,
            endpoints=endpoints,
            definition=definition,
            sort_order=sort_order,
            is_active=is_active,
            request_options=request_options,
        )
        return _response.data
