# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.mcp_server_tool_auth_type import McpServerToolAuthType
from ..types.mcp_server_tool_kind import McpServerToolKind
from .raw_client import AsyncRawMcpServersClient, RawMcpServersClient
from .types.create_mcp_server_response import CreateMcpServerResponse
from .types.create_mcp_server_tool_response import CreateMcpServerToolResponse
from .types.list_mcp_server_tools_response import ListMcpServerToolsResponse
from .types.list_mcp_servers_response import ListMcpServersResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class McpServersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMcpServersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMcpServersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMcpServersClient
        """
        return self._raw_client

    def list_mcp_servers(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListMcpServersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServersResponse
            Danh sách MCP server

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.list_mcp_servers()
        """
        _response = self._raw_client.list_mcp_servers(request_options=request_options)
        return _response.data

    def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerResponse:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerResponse
            MCP server đã tạo

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.create_mcp_server(
            name="name",
        )
        """
        _response = self._raw_client.create_mcp_server(
            name=name, idempotency_key=idempotency_key, description=description, request_options=request_options
        )
        return _response.data

    def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServerToolsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServerToolsResponse
            Danh sách tool

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.list_mcp_server_tools(
            id="id",
        )
        """
        _response = self._raw_client.list_mcp_server_tools(id, request_options=request_options)
        return _response.data

    def create_mcp_server_tool(
        self,
        id_: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        id: typing.Optional[str] = OMIT,
        mcp_server_id: typing.Optional[str] = OMIT,
        kind: typing.Optional[McpServerToolKind] = OMIT,
        slug: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolAuthType] = OMIT,
        auth_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        endpoints: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerToolResponse:
        """
        Parameters
        ----------
        id_ : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        id : typing.Optional[str]

        mcp_server_id : typing.Optional[str]

        kind : typing.Optional[McpServerToolKind]

        slug : typing.Optional[str]

        display_name : typing.Optional[str]

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolAuthType]

        auth_config : typing.Optional[typing.Dict[str, typing.Any]]
            Thông tin xác thực (có thể chứa secret — không phơi raw token ở list).

        endpoints : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerToolResponse
            Tool đã tạo

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.mcp_servers.create_mcp_server_tool(
            id_="id",
        )
        """
        _response = self._raw_client.create_mcp_server_tool(
            id_,
            idempotency_key=idempotency_key,
            id=id,
            mcp_server_id=mcp_server_id,
            kind=kind,
            slug=slug,
            display_name=display_name,
            description=description,
            base_url=base_url,
            auth_type=auth_type,
            auth_config=auth_config,
            endpoints=endpoints,
            sort_order=sort_order,
            is_active=is_active,
            created_at=created_at,
            updated_at=updated_at,
            request_options=request_options,
        )
        return _response.data


class AsyncMcpServersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMcpServersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMcpServersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMcpServersClient
        """
        return self._raw_client

    async def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServersResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServersResponse
            Danh sách MCP server

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.list_mcp_servers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_mcp_servers(request_options=request_options)
        return _response.data

    async def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerResponse:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerResponse
            MCP server đã tạo

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.create_mcp_server(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_mcp_server(
            name=name, idempotency_key=idempotency_key, description=description, request_options=request_options
        )
        return _response.data

    async def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMcpServerToolsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMcpServerToolsResponse
            Danh sách tool

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.list_mcp_server_tools(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_mcp_server_tools(id, request_options=request_options)
        return _response.data

    async def create_mcp_server_tool(
        self,
        id_: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        id: typing.Optional[str] = OMIT,
        mcp_server_id: typing.Optional[str] = OMIT,
        kind: typing.Optional[McpServerToolKind] = OMIT,
        slug: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolAuthType] = OMIT,
        auth_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        endpoints: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateMcpServerToolResponse:
        """
        Parameters
        ----------
        id_ : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        id : typing.Optional[str]

        mcp_server_id : typing.Optional[str]

        kind : typing.Optional[McpServerToolKind]

        slug : typing.Optional[str]

        display_name : typing.Optional[str]

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolAuthType]

        auth_config : typing.Optional[typing.Dict[str, typing.Any]]
            Thông tin xác thực (có thể chứa secret — không phơi raw token ở list).

        endpoints : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateMcpServerToolResponse
            Tool đã tạo

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.mcp_servers.create_mcp_server_tool(
                id_="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_mcp_server_tool(
            id_,
            idempotency_key=idempotency_key,
            id=id,
            mcp_server_id=mcp_server_id,
            kind=kind,
            slug=slug,
            display_name=display_name,
            description=description,
            base_url=base_url,
            auth_type=auth_type,
            auth_config=auth_config,
            endpoints=endpoints,
            sort_order=sort_order,
            is_active=is_active,
            created_at=created_at,
            updated_at=updated_at,
            request_options=request_options,
        )
        return _response.data
