# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..types.mcp_server_tool_auth_type import McpServerToolAuthType
from ..types.mcp_server_tool_kind import McpServerToolKind
from .types.create_mcp_server_response import CreateMcpServerResponse
from .types.create_mcp_server_tool_response import CreateMcpServerToolResponse
from .types.list_mcp_server_tools_response import ListMcpServerToolsResponse
from .types.list_mcp_servers_response import ListMcpServersResponse
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMcpServersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListMcpServersResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMcpServersResponse]
            Danh sách MCP server
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServersResponse,
                    parse_obj_as(
                        type_=ListMcpServersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateMcpServerResponse]:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateMcpServerResponse]
            MCP server đã tạo
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerResponse,
                    parse_obj_as(
                        type_=CreateMcpServerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListMcpServerToolsResponse]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMcpServerToolsResponse]
            Danh sách tool
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServerToolsResponse,
                    parse_obj_as(
                        type_=ListMcpServerToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_mcp_server_tool(
        self,
        id_: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        id: typing.Optional[str] = OMIT,
        mcp_server_id: typing.Optional[str] = OMIT,
        kind: typing.Optional[McpServerToolKind] = OMIT,
        slug: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolAuthType] = OMIT,
        auth_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        endpoints: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateMcpServerToolResponse]:
        """
        Parameters
        ----------
        id_ : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        id : typing.Optional[str]

        mcp_server_id : typing.Optional[str]

        kind : typing.Optional[McpServerToolKind]

        slug : typing.Optional[str]

        display_name : typing.Optional[str]

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolAuthType]

        auth_config : typing.Optional[typing.Dict[str, typing.Any]]
            Thông tin xác thực (có thể chứa secret — không phơi raw token ở list).

        endpoints : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateMcpServerToolResponse]
            Tool đã tạo
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id_)}/tools",
            method="POST",
            json={
                "id": id,
                "mcp_server_id": mcp_server_id,
                "kind": kind,
                "slug": slug,
                "display_name": display_name,
                "description": description,
                "base_url": base_url,
                "auth_type": auth_type,
                "auth_config": auth_config,
                "endpoints": endpoints,
                "sort_order": sort_order,
                "is_active": is_active,
                "created_at": created_at,
                "updated_at": updated_at,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerToolResponse,
                    parse_obj_as(
                        type_=CreateMcpServerToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMcpServersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListMcpServersResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMcpServersResponse]
            Danh sách MCP server
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServersResponse,
                    parse_obj_as(
                        type_=ListMcpServersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateMcpServerResponse]:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateMcpServerResponse]
            MCP server đã tạo
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerResponse,
                    parse_obj_as(
                        type_=CreateMcpServerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListMcpServerToolsResponse]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMcpServerToolsResponse]
            Danh sách tool
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServerToolsResponse,
                    parse_obj_as(
                        type_=ListMcpServerToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_mcp_server_tool(
        self,
        id_: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        id: typing.Optional[str] = OMIT,
        mcp_server_id: typing.Optional[str] = OMIT,
        kind: typing.Optional[McpServerToolKind] = OMIT,
        slug: typing.Optional[str] = OMIT,
        display_name: typing.Optional[str] = OMIT,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolAuthType] = OMIT,
        auth_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        endpoints: typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        created_at: typing.Optional[dt.datetime] = OMIT,
        updated_at: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateMcpServerToolResponse]:
        """
        Parameters
        ----------
        id_ : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        id : typing.Optional[str]

        mcp_server_id : typing.Optional[str]

        kind : typing.Optional[McpServerToolKind]

        slug : typing.Optional[str]

        display_name : typing.Optional[str]

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolAuthType]

        auth_config : typing.Optional[typing.Dict[str, typing.Any]]
            Thông tin xác thực (có thể chứa secret — không phơi raw token ở list).

        endpoints : typing.Optional[typing.Sequence[typing.Dict[str, typing.Any]]]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        created_at : typing.Optional[dt.datetime]

        updated_at : typing.Optional[dt.datetime]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateMcpServerToolResponse]
            Tool đã tạo
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id_)}/tools",
            method="POST",
            json={
                "id": id,
                "mcp_server_id": mcp_server_id,
                "kind": kind,
                "slug": slug,
                "display_name": display_name,
                "description": description,
                "base_url": base_url,
                "auth_type": auth_type,
                "auth_config": auth_config,
                "endpoints": endpoints,
                "sort_order": sort_order,
                "is_active": is_active,
                "created_at": created_at,
                "updated_at": updated_at,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerToolResponse,
                    parse_obj_as(
                        type_=CreateMcpServerToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
