# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..errors.bad_request_error import BadRequestError
from ..errors.forbidden_error import ForbiddenError
from ..errors.not_found_error import NotFoundError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.mcp_auth_config import McpAuthConfig
from ..types.mcp_endpoint import McpEndpoint
from ..types.mcp_tool_definition import McpToolDefinition
from .types.create_mcp_server_response import CreateMcpServerResponse
from .types.create_mcp_server_tool_response import CreateMcpServerToolResponse
from .types.list_mcp_server_tools_response import ListMcpServerToolsResponse
from .types.list_mcp_servers_response import ListMcpServersResponse
from .types.mcp_server_tool_create_request_auth_type import McpServerToolCreateRequestAuthType
from .types.mcp_server_tool_create_request_kind import McpServerToolCreateRequestKind
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawMcpServersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListMcpServersResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMcpServersResponse]
            Danh sách MCP server
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServersResponse,
                    parse_obj_as(
                        type_=ListMcpServersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateMcpServerResponse]:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateMcpServerResponse]
            MCP server đã tạo
        """
        _response = self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerResponse,
                    parse_obj_as(
                        type_=CreateMcpServerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[ListMcpServerToolsResponse]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ListMcpServerToolsResponse]
            Danh sách tool
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServerToolsResponse,
                    parse_obj_as(
                        type_=ListMcpServerToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_mcp_server_tool(
        self,
        id: str,
        *,
        kind: McpServerToolCreateRequestKind,
        slug: str,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        rest_resource_path: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolCreateRequestAuthType] = OMIT,
        auth_config: typing.Optional[McpAuthConfig] = OMIT,
        endpoints: typing.Optional[typing.Sequence[McpEndpoint]] = OMIT,
        definition: typing.Optional[McpToolDefinition] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[CreateMcpServerToolResponse]:
        """
        Parameters
        ----------
        id : str

        kind : McpServerToolCreateRequestKind

        slug : str

        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        rest_resource_path : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolCreateRequestAuthType]

        auth_config : typing.Optional[McpAuthConfig]

        endpoints : typing.Optional[typing.Sequence[McpEndpoint]]

        definition : typing.Optional[McpToolDefinition]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[CreateMcpServerToolResponse]
            Tool đã tạo
        """
        _response = self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="POST",
            json={
                "kind": kind,
                "slug": slug,
                "display_name": display_name,
                "description": description,
                "base_url": base_url,
                "rest_resource_path": rest_resource_path,
                "auth_type": auth_type,
                "auth_config": convert_and_respect_annotation_metadata(
                    object_=auth_config, annotation=McpAuthConfig, direction="write"
                ),
                "endpoints": convert_and_respect_annotation_metadata(
                    object_=endpoints, annotation=typing.Sequence[McpEndpoint], direction="write"
                ),
                "definition": convert_and_respect_annotation_metadata(
                    object_=definition, annotation=McpToolDefinition, direction="write"
                ),
                "sort_order": sort_order,
                "is_active": is_active,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerToolResponse,
                    parse_obj_as(
                        type_=CreateMcpServerToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawMcpServersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_mcp_servers(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListMcpServersResponse]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMcpServersResponse]
            Danh sách MCP server
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServersResponse,
                    parse_obj_as(
                        type_=ListMcpServersResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_mcp_server(
        self,
        *,
        name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateMcpServerResponse]:
        """
        Parameters
        ----------
        name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateMcpServerResponse]
            MCP server đã tạo
        """
        _response = await self._client_wrapper.httpx_client.request(
            "api/v1/mcp-servers",
            method="POST",
            json={
                "name": name,
                "description": description,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerResponse,
                    parse_obj_as(
                        type_=CreateMcpServerResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def list_mcp_server_tools(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ListMcpServerToolsResponse]:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ListMcpServerToolsResponse]
            Danh sách tool
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ListMcpServerToolsResponse,
                    parse_obj_as(
                        type_=ListMcpServerToolsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_mcp_server_tool(
        self,
        id: str,
        *,
        kind: McpServerToolCreateRequestKind,
        slug: str,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        description: typing.Optional[str] = OMIT,
        base_url: typing.Optional[str] = OMIT,
        rest_resource_path: typing.Optional[str] = OMIT,
        auth_type: typing.Optional[McpServerToolCreateRequestAuthType] = OMIT,
        auth_config: typing.Optional[McpAuthConfig] = OMIT,
        endpoints: typing.Optional[typing.Sequence[McpEndpoint]] = OMIT,
        definition: typing.Optional[McpToolDefinition] = OMIT,
        sort_order: typing.Optional[int] = OMIT,
        is_active: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[CreateMcpServerToolResponse]:
        """
        Parameters
        ----------
        id : str

        kind : McpServerToolCreateRequestKind

        slug : str

        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        description : typing.Optional[str]

        base_url : typing.Optional[str]

        rest_resource_path : typing.Optional[str]

        auth_type : typing.Optional[McpServerToolCreateRequestAuthType]

        auth_config : typing.Optional[McpAuthConfig]

        endpoints : typing.Optional[typing.Sequence[McpEndpoint]]

        definition : typing.Optional[McpToolDefinition]

        sort_order : typing.Optional[int]

        is_active : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[CreateMcpServerToolResponse]
            Tool đã tạo
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"api/v1/mcp-servers/{encode_path_param(id)}/tools",
            method="POST",
            json={
                "kind": kind,
                "slug": slug,
                "display_name": display_name,
                "description": description,
                "base_url": base_url,
                "rest_resource_path": rest_resource_path,
                "auth_type": auth_type,
                "auth_config": convert_and_respect_annotation_metadata(
                    object_=auth_config, annotation=McpAuthConfig, direction="write"
                ),
                "endpoints": convert_and_respect_annotation_metadata(
                    object_=endpoints, annotation=typing.Sequence[McpEndpoint], direction="write"
                ),
                "definition": convert_and_respect_annotation_metadata(
                    object_=definition, annotation=McpToolDefinition, direction="write"
                ),
                "sort_order": sort_order,
                "is_active": is_active,
            },
            headers={
                "content-type": "application/json",
                "Idempotency-Key": str(idempotency_key) if idempotency_key is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    CreateMcpServerToolResponse,
                    parse_obj_as(
                        type_=CreateMcpServerToolResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 403:
                raise ForbiddenError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 404:
                raise NotFoundError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
