# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawOrganizationsClient, RawOrganizationsClient
from .types.get_organization_response import GetOrganizationResponse
from .types.list_organization_members_response import ListOrganizationMembersResponse


class OrganizationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawOrganizationsClient
        """
        return self._raw_client

    def get_organization(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrganizationResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.organizations.get_organization(
            id="id",
        )
        """
        _response = self._raw_client.get_organization(id, request_options=request_options)
        return _response.data

    def list_organization_members(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListOrganizationMembersResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListOrganizationMembersResponse
            Danh sách thành viên

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.organizations.list_organization_members(
            id="id",
        )
        """
        _response = self._raw_client.list_organization_members(id, request_options=request_options)
        return _response.data


class AsyncOrganizationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawOrganizationsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawOrganizationsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawOrganizationsClient
        """
        return self._raw_client

    async def get_organization(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetOrganizationResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetOrganizationResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organizations.get_organization(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_organization(id, request_options=request_options)
        return _response.data

    async def list_organization_members(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ListOrganizationMembersResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListOrganizationMembersResponse
            Danh sách thành viên

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.organizations.list_organization_members(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_organization_members(id, request_options=request_options)
        return _response.data
