# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...types.envelope_status import EnvelopeStatus
from ...types.mcp_server_tool import McpServerTool


class CreateMcpServerToolResponse(UniversalBaseModel):
    data: typing.Optional[McpServerTool] = None
    status: EnvelopeStatus
    code: str
    message: str
    trace_id: str
    timestamp: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
