# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.channel_config import ChannelConfig
from ..types.model_list import ModelList
from .raw_client import AsyncRawAgentsClient, RawAgentsClient
from .types.create_agent_response import CreateAgentResponse
from .types.delete_agent_response import DeleteAgentResponse
from .types.get_agent_channels_response import GetAgentChannelsResponse
from .types.get_agent_response import GetAgentResponse
from .types.list_agents_response import ListAgentsResponse
from .types.start_agent_response import StartAgentResponse
from .types.stop_agent_response import StopAgentResponse
from .types.update_agent_channels_response import UpdateAgentChannelsResponse
from .types.update_agent_response import UpdateAgentResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AgentsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAgentsClient
        """
        return self._raw_client

    def list_agents(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAgentsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Danh sách agent

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.list_agents()
        """
        _response = self._raw_client.list_agents(request_options=request_options)
        return _response.data

    def create_agent(
        self,
        *,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        llm_provider: typing.Optional[str] = OMIT,
        llm_model: typing.Optional[str] = OMIT,
        llm_base_url: typing.Optional[str] = OMIT,
        llm_api_key: typing.Optional[str] = OMIT,
        knowledge_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled_tools: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_server_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_tool_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentResponse:
        """
        Parameters
        ----------
        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        llm_provider : typing.Optional[str]

        llm_model : typing.Optional[str]

        llm_base_url : typing.Optional[str]

        llm_api_key : typing.Optional[str]

        knowledge_ids : typing.Optional[typing.Sequence[str]]
            UUID các knowledge item gắn agent (điền vào dtg_knowledge_ids).

        enabled_tools : typing.Optional[typing.Sequence[str]]
            ID tool từ catalog (dtg_enabled_tools), vd knowledge_rag.

        mcp_dynamic_server_ids : typing.Optional[typing.Sequence[str]]
            UUID MCP server động (apimcp) gắn agent.

        mcp_dynamic_tool_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Filter tool expose cho agent (Dai Agent) theo từng MCP server động (khóa = UUID server).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentResponse
            Chi tiết agent

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.create_agent(
            display_name="display_name",
        )
        """
        _response = self._raw_client.create_agent(
            display_name=display_name,
            idempotency_key=idempotency_key,
            llm_provider=llm_provider,
            llm_model=llm_model,
            llm_base_url=llm_base_url,
            llm_api_key=llm_api_key,
            knowledge_ids=knowledge_ids,
            enabled_tools=enabled_tools,
            mcp_dynamic_server_ids=mcp_dynamic_server_ids,
            mcp_dynamic_tool_filter=mcp_dynamic_tool_filter,
            request_options=request_options,
        )
        return _response.data

    def get_agent(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAgentResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentResponse
            Chi tiết agent

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.get_agent(
            id="id",
        )
        """
        _response = self._raw_client.get_agent(id, request_options=request_options)
        return _response.data

    def delete_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAgentResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.delete_agent(
            id="id",
        )
        """
        _response = self._raw_client.delete_agent(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        llm_provider: typing.Optional[str] = OMIT,
        llm_model: typing.Optional[str] = OMIT,
        llm_base_url: typing.Optional[str] = OMIT,
        llm_api_key: typing.Optional[str] = OMIT,
        knowledge_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled_tools: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_server_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_tool_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        display_name : typing.Optional[str]

        llm_provider : typing.Optional[str]

        llm_model : typing.Optional[str]

        llm_base_url : typing.Optional[str]

        llm_api_key : typing.Optional[str]

        knowledge_ids : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        enabled_tools : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        mcp_dynamic_server_ids : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        mcp_dynamic_tool_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Omit/null = giữ nguyên; {} = xoá.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Chi tiết agent

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.update_agent(
            id="id",
        )
        """
        _response = self._raw_client.update_agent(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            llm_provider=llm_provider,
            llm_model=llm_model,
            llm_base_url=llm_base_url,
            llm_api_key=llm_api_key,
            knowledge_ids=knowledge_ids,
            enabled_tools=enabled_tools,
            mcp_dynamic_server_ids=mcp_dynamic_server_ids,
            mcp_dynamic_tool_filter=mcp_dynamic_tool_filter,
            request_options=request_options,
        )
        return _response.data

    def start_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartAgentResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.start_agent(
            id="id",
        )
        """
        _response = self._raw_client.start_agent(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def stop_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StopAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StopAgentResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.stop_agent(
            id="id",
        )
        """
        _response = self._raw_client.stop_agent(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def get_agent_channels(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentChannelsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChannelsResponse
            Danh sách kênh

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.get_agent_channels(
            id="id",
        )
        """
        _response = self._raw_client.get_agent_channels(id, request_options=request_options)
        return _response.data

    def update_agent_channels(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        channels: typing.Optional[typing.Sequence[ChannelConfig]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentChannelsResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        channels : typing.Optional[typing.Sequence[ChannelConfig]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentChannelsResponse
            Cấu hình kênh đã lưu

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.update_agent_channels(
            id="id",
        )
        """
        _response = self._raw_client.update_agent_channels(
            id, idempotency_key=idempotency_key, channels=channels, request_options=request_options
        )
        return _response.data

    def list_agent_models(self, *, request_options: typing.Optional[RequestOptions] = None) -> ModelList:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelList
            Danh sách models

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.agents.list_agent_models()
        """
        _response = self._raw_client.list_agent_models(request_options=request_options)
        return _response.data


class AsyncAgentsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAgentsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAgentsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAgentsClient
        """
        return self._raw_client

    async def list_agents(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListAgentsResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListAgentsResponse
            Danh sách agent

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.list_agents()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agents(request_options=request_options)
        return _response.data

    async def create_agent(
        self,
        *,
        display_name: str,
        idempotency_key: typing.Optional[str] = None,
        llm_provider: typing.Optional[str] = OMIT,
        llm_model: typing.Optional[str] = OMIT,
        llm_base_url: typing.Optional[str] = OMIT,
        llm_api_key: typing.Optional[str] = OMIT,
        knowledge_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled_tools: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_server_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_tool_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateAgentResponse:
        """
        Parameters
        ----------
        display_name : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        llm_provider : typing.Optional[str]

        llm_model : typing.Optional[str]

        llm_base_url : typing.Optional[str]

        llm_api_key : typing.Optional[str]

        knowledge_ids : typing.Optional[typing.Sequence[str]]
            UUID các knowledge item gắn agent (điền vào dtg_knowledge_ids).

        enabled_tools : typing.Optional[typing.Sequence[str]]
            ID tool từ catalog (dtg_enabled_tools), vd knowledge_rag.

        mcp_dynamic_server_ids : typing.Optional[typing.Sequence[str]]
            UUID MCP server động (apimcp) gắn agent.

        mcp_dynamic_tool_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Filter tool expose cho agent (Dai Agent) theo từng MCP server động (khóa = UUID server).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateAgentResponse
            Chi tiết agent

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.create_agent(
                display_name="display_name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_agent(
            display_name=display_name,
            idempotency_key=idempotency_key,
            llm_provider=llm_provider,
            llm_model=llm_model,
            llm_base_url=llm_base_url,
            llm_api_key=llm_api_key,
            knowledge_ids=knowledge_ids,
            enabled_tools=enabled_tools,
            mcp_dynamic_server_ids=mcp_dynamic_server_ids,
            mcp_dynamic_tool_filter=mcp_dynamic_tool_filter,
            request_options=request_options,
        )
        return _response.data

    async def get_agent(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetAgentResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentResponse
            Chi tiết agent

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get_agent(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent(id, request_options=request_options)
        return _response.data

    async def delete_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteAgentResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.delete_agent(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_agent(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        llm_provider: typing.Optional[str] = OMIT,
        llm_model: typing.Optional[str] = OMIT,
        llm_base_url: typing.Optional[str] = OMIT,
        llm_api_key: typing.Optional[str] = OMIT,
        knowledge_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        enabled_tools: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_server_ids: typing.Optional[typing.Sequence[str]] = OMIT,
        mcp_dynamic_tool_filter: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        display_name : typing.Optional[str]

        llm_provider : typing.Optional[str]

        llm_model : typing.Optional[str]

        llm_base_url : typing.Optional[str]

        llm_api_key : typing.Optional[str]

        knowledge_ids : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        enabled_tools : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        mcp_dynamic_server_ids : typing.Optional[typing.Sequence[str]]
            Omit/null = giữ nguyên; [] = xoá.

        mcp_dynamic_tool_filter : typing.Optional[typing.Dict[str, typing.Any]]
            Omit/null = giữ nguyên; {} = xoá.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentResponse
            Chi tiết agent

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.update_agent(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_agent(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            llm_provider=llm_provider,
            llm_model=llm_model,
            llm_base_url=llm_base_url,
            llm_api_key=llm_api_key,
            knowledge_ids=knowledge_ids,
            enabled_tools=enabled_tools,
            mcp_dynamic_server_ids=mcp_dynamic_server_ids,
            mcp_dynamic_tool_filter=mcp_dynamic_tool_filter,
            request_options=request_options,
        )
        return _response.data

    async def start_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StartAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StartAgentResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.start_agent(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.start_agent(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def stop_agent(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> StopAgentResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        StopAgentResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.stop_agent(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.stop_agent(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def get_agent_channels(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetAgentChannelsResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetAgentChannelsResponse
            Danh sách kênh

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.get_agent_channels(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_agent_channels(id, request_options=request_options)
        return _response.data

    async def update_agent_channels(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        channels: typing.Optional[typing.Sequence[ChannelConfig]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateAgentChannelsResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        channels : typing.Optional[typing.Sequence[ChannelConfig]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateAgentChannelsResponse
            Cấu hình kênh đã lưu

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.update_agent_channels(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_agent_channels(
            id, idempotency_key=idempotency_key, channels=channels, request_options=request_options
        )
        return _response.data

    async def list_agent_models(self, *, request_options: typing.Optional[RequestOptions] = None) -> ModelList:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ModelList
            Danh sách models

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.agents.list_agent_models()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_agent_models(request_options=request_options)
        return _response.data
