# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawCamerasClient, RawCamerasClient
from .types.camera_create_request_vendor import CameraCreateRequestVendor
from .types.camera_update_request_vendor import CameraUpdateRequestVendor
from .types.create_camera_response import CreateCameraResponse
from .types.delete_camera_response import DeleteCameraResponse
from .types.get_camera_response import GetCameraResponse
from .types.list_cameras_response import ListCamerasResponse
from .types.update_camera_response import UpdateCameraResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CamerasClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCamerasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCamerasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCamerasClient
        """
        return self._raw_client

    def list_cameras(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListCamerasResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCamerasResponse
            Danh sách camera

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.cameras.list_cameras()
        """
        _response = self._raw_client.list_cameras(request_options=request_options)
        return _response.data

    def create_camera(
        self,
        *,
        display_name: str,
        vendor: CameraCreateRequestVendor,
        rtsp_url: str,
        idempotency_key: typing.Optional[str] = None,
        rtsp_username: typing.Optional[str] = OMIT,
        rtsp_password: typing.Optional[str] = OMIT,
        vendor_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCameraResponse:
        """
        Parameters
        ----------
        display_name : str

        vendor : CameraCreateRequestVendor

        rtsp_url : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        rtsp_username : typing.Optional[str]

        rtsp_password : typing.Optional[str]
            Chỉ gửi khi tạo; không bao giờ trả về trong response.

        vendor_config : typing.Optional[typing.Dict[str, typing.Any]]

        enabled : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCameraResponse
            Chi tiết camera

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.cameras.create_camera(
            display_name="display_name",
            vendor="generic_rtsp",
            rtsp_url="rtsp_url",
        )
        """
        _response = self._raw_client.create_camera(
            display_name=display_name,
            vendor=vendor,
            rtsp_url=rtsp_url,
            idempotency_key=idempotency_key,
            rtsp_username=rtsp_username,
            rtsp_password=rtsp_password,
            vendor_config=vendor_config,
            enabled=enabled,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    def get_camera(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetCameraResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCameraResponse
            Chi tiết camera

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.cameras.get_camera(
            id="id",
        )
        """
        _response = self._raw_client.get_camera(id, request_options=request_options)
        return _response.data

    def delete_camera(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteCameraResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCameraResponse
            OK

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.cameras.delete_camera(
            id="id",
        )
        """
        _response = self._raw_client.delete_camera(id, idempotency_key=idempotency_key, request_options=request_options)
        return _response.data

    def update_camera(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        vendor: typing.Optional[CameraUpdateRequestVendor] = OMIT,
        rtsp_url: typing.Optional[str] = OMIT,
        rtsp_username: typing.Optional[str] = OMIT,
        rtsp_password: typing.Optional[str] = OMIT,
        vendor_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCameraResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        display_name : typing.Optional[str]

        vendor : typing.Optional[CameraUpdateRequestVendor]

        rtsp_url : typing.Optional[str]

        rtsp_username : typing.Optional[str]

        rtsp_password : typing.Optional[str]
            Rỗng/omit = giữ mật khẩu cũ; gửi giá trị mới = ghi đè.

        vendor_config : typing.Optional[typing.Dict[str, typing.Any]]

        enabled : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCameraResponse
            Chi tiết camera

        Examples
        --------
        from dtgsoft import DtgAgentSdk

        client = DtgAgentSdk(
            token="YOUR_TOKEN",
        )
        client.cameras.update_camera(
            id="id",
        )
        """
        _response = self._raw_client.update_camera(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            vendor=vendor,
            rtsp_url=rtsp_url,
            rtsp_username=rtsp_username,
            rtsp_password=rtsp_password,
            vendor_config=vendor_config,
            enabled=enabled,
            notes=notes,
            request_options=request_options,
        )
        return _response.data


class AsyncCamerasClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCamerasClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCamerasClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCamerasClient
        """
        return self._raw_client

    async def list_cameras(self, *, request_options: typing.Optional[RequestOptions] = None) -> ListCamerasResponse:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCamerasResponse
            Danh sách camera

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cameras.list_cameras()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_cameras(request_options=request_options)
        return _response.data

    async def create_camera(
        self,
        *,
        display_name: str,
        vendor: CameraCreateRequestVendor,
        rtsp_url: str,
        idempotency_key: typing.Optional[str] = None,
        rtsp_username: typing.Optional[str] = OMIT,
        rtsp_password: typing.Optional[str] = OMIT,
        vendor_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCameraResponse:
        """
        Parameters
        ----------
        display_name : str

        vendor : CameraCreateRequestVendor

        rtsp_url : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        rtsp_username : typing.Optional[str]

        rtsp_password : typing.Optional[str]
            Chỉ gửi khi tạo; không bao giờ trả về trong response.

        vendor_config : typing.Optional[typing.Dict[str, typing.Any]]

        enabled : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCameraResponse
            Chi tiết camera

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cameras.create_camera(
                display_name="display_name",
                vendor="generic_rtsp",
                rtsp_url="rtsp_url",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_camera(
            display_name=display_name,
            vendor=vendor,
            rtsp_url=rtsp_url,
            idempotency_key=idempotency_key,
            rtsp_username=rtsp_username,
            rtsp_password=rtsp_password,
            vendor_config=vendor_config,
            enabled=enabled,
            notes=notes,
            request_options=request_options,
        )
        return _response.data

    async def get_camera(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetCameraResponse:
        """
        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetCameraResponse
            Chi tiết camera

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cameras.get_camera(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_camera(id, request_options=request_options)
        return _response.data

    async def delete_camera(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> DeleteCameraResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DeleteCameraResponse
            OK

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cameras.delete_camera(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_camera(
            id, idempotency_key=idempotency_key, request_options=request_options
        )
        return _response.data

    async def update_camera(
        self,
        id: str,
        *,
        idempotency_key: typing.Optional[str] = None,
        display_name: typing.Optional[str] = OMIT,
        vendor: typing.Optional[CameraUpdateRequestVendor] = OMIT,
        rtsp_url: typing.Optional[str] = OMIT,
        rtsp_username: typing.Optional[str] = OMIT,
        rtsp_password: typing.Optional[str] = OMIT,
        vendor_config: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        enabled: typing.Optional[bool] = OMIT,
        notes: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UpdateCameraResponse:
        """
        Parameters
        ----------
        id : str

        idempotency_key : typing.Optional[str]
            Idempotency key cho mutation (tránh double-submit).

        display_name : typing.Optional[str]

        vendor : typing.Optional[CameraUpdateRequestVendor]

        rtsp_url : typing.Optional[str]

        rtsp_username : typing.Optional[str]

        rtsp_password : typing.Optional[str]
            Rỗng/omit = giữ mật khẩu cũ; gửi giá trị mới = ghi đè.

        vendor_config : typing.Optional[typing.Dict[str, typing.Any]]

        enabled : typing.Optional[bool]

        notes : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UpdateCameraResponse
            Chi tiết camera

        Examples
        --------
        import asyncio

        from dtgsoft import AsyncDtgAgentSdk

        client = AsyncDtgAgentSdk(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cameras.update_camera(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_camera(
            id,
            idempotency_key=idempotency_key,
            display_name=display_name,
            vendor=vendor,
            rtsp_url=rtsp_url,
            rtsp_username=rtsp_username,
            rtsp_password=rtsp_password,
            vendor_config=vendor_config,
            enabled=enabled,
            notes=notes,
            request_options=request_options,
        )
        return _response.data
