# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..core.serialization import convert_and_respect_annotation_metadata
from ..types.chat_completion import ChatCompletion
from ..types.chat_message import ChatMessage
from ..types.model_list import ModelList
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawGatewayClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def list_models(self, *, request_options: typing.Optional[RequestOptions] = None) -> HttpResponse[ModelList]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ModelList]
            Danh sách models (OpenAI-compatible, không bọc envelope)
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelList,
                    parse_obj_as(
                        type_=ModelList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    def create_chat_completion(
        self,
        *,
        model: str,
        messages: typing.Sequence[ChatMessage],
        hermes_session_id: typing.Optional[str] = None,
        hermes_thread_id: typing.Optional[str] = None,
        temperature: typing.Optional[float] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        thread_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[ChatCompletion]:
        """
        Parameters
        ----------
        model : str
            ID của agent (UUID).

        messages : typing.Sequence[ChatMessage]

        hermes_session_id : typing.Optional[str]
            Session tùy chỉnh phía client.

        hermes_thread_id : typing.Optional[str]
            Thread tùy chỉnh phía client.

        temperature : typing.Optional[float]

        stream : typing.Optional[bool]

        session_id : typing.Optional[str]

        thread_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[ChatCompletion]
            ChatCompletion (hoặc SSE stream khi stream=true)
        """
        _response = self._client_wrapper.httpx_client.request(
            "v1/chat/completions",
            method="POST",
            json={
                "model": model,
                "messages": convert_and_respect_annotation_metadata(
                    object_=messages, annotation=typing.Sequence[ChatMessage], direction="write"
                ),
                "temperature": temperature,
                "stream": stream,
                "session_id": session_id,
                "thread_id": thread_id,
            },
            headers={
                "content-type": "application/json",
                "X-Hermes-Session-Id": str(hermes_session_id) if hermes_session_id is not None else None,
                "X-Hermes-Thread-Id": str(hermes_thread_id) if hermes_thread_id is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ChatCompletion,
                    parse_obj_as(
                        type_=ChatCompletion,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawGatewayClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def list_models(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[ModelList]:
        """
        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ModelList]
            Danh sách models (OpenAI-compatible, không bọc envelope)
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/models",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ModelList,
                    parse_obj_as(
                        type_=ModelList,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)

    async def create_chat_completion(
        self,
        *,
        model: str,
        messages: typing.Sequence[ChatMessage],
        hermes_session_id: typing.Optional[str] = None,
        hermes_thread_id: typing.Optional[str] = None,
        temperature: typing.Optional[float] = OMIT,
        stream: typing.Optional[bool] = OMIT,
        session_id: typing.Optional[str] = OMIT,
        thread_id: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[ChatCompletion]:
        """
        Parameters
        ----------
        model : str
            ID của agent (UUID).

        messages : typing.Sequence[ChatMessage]

        hermes_session_id : typing.Optional[str]
            Session tùy chỉnh phía client.

        hermes_thread_id : typing.Optional[str]
            Thread tùy chỉnh phía client.

        temperature : typing.Optional[float]

        stream : typing.Optional[bool]

        session_id : typing.Optional[str]

        thread_id : typing.Optional[str]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[ChatCompletion]
            ChatCompletion (hoặc SSE stream khi stream=true)
        """
        _response = await self._client_wrapper.httpx_client.request(
            "v1/chat/completions",
            method="POST",
            json={
                "model": model,
                "messages": convert_and_respect_annotation_metadata(
                    object_=messages, annotation=typing.Sequence[ChatMessage], direction="write"
                ),
                "temperature": temperature,
                "stream": stream,
                "session_id": session_id,
                "thread_id": thread_id,
            },
            headers={
                "content-type": "application/json",
                "X-Hermes-Session-Id": str(hermes_session_id) if hermes_session_id is not None else None,
                "X-Hermes-Thread-Id": str(hermes_thread_id) if hermes_thread_id is not None else None,
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    ChatCompletion,
                    parse_obj_as(
                        type_=ChatCompletion,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
