# This file was auto-generated by Fern from our API Definition.

# isort: skip_file

import typing
from importlib import import_module

if typing.TYPE_CHECKING:
    from .types import (
        Agent,
        AgentStatus,
        ApiKey,
        ApiKeyCreateResponse,
        ChannelConfig,
        ChannelConfigType,
        ChatCompletion,
        ChatCompletionUsage,
        ChatMessage,
        ChatMessageRole,
        Envelope,
        EnvelopeStatus,
        Knowledge,
        KnowledgeContentType,
        KnowledgeDetail,
        McpServer,
        McpServerTool,
        McpServerToolAuthType,
        McpServerToolKind,
        Model,
        ModelList,
        OkResponse,
        Organization,
        OrganizationMember,
        OrganizationMemberRole,
    )
    from . import agents, api_keys, gateway, knowledge, mcp_servers, organizations
    from ._default_clients import DefaultAioHttpClient, DefaultAsyncHttpxClient
    from .agents import (
        CreateAgentResponse,
        DeleteAgentResponse,
        GetAgentChannelsResponse,
        GetAgentResponse,
        ListAgentsResponse,
        StartAgentResponse,
        StopAgentResponse,
        UpdateAgentChannelsResponse,
        UpdateAgentResponse,
    )
    from .api_keys import CreateApiKeyResponse, ListApiKeysResponse, RevokeApiKeyResponse
    from .client import AsyncDtgAgentSdk, DtgAgentSdk
    from .environment import DtgAgentSdkEnvironment
    from .knowledge import (
        CreateKnowledgeResponse,
        DeleteKnowledgeResponse,
        GetKnowledgeResponse,
        KnowledgeCreateRequestContentType,
        ListKnowledgeResponse,
    )
    from .mcp_servers import (
        CreateMcpServerResponse,
        CreateMcpServerToolResponse,
        ListMcpServerToolsResponse,
        ListMcpServersResponse,
    )
    from .organizations import GetOrganizationResponse, ListOrganizationMembersResponse
    from .version import __version__
_dynamic_imports: typing.Dict[str, str] = {
    "Agent": ".types",
    "AgentStatus": ".types",
    "ApiKey": ".types",
    "ApiKeyCreateResponse": ".types",
    "AsyncDtgAgentSdk": ".client",
    "ChannelConfig": ".types",
    "ChannelConfigType": ".types",
    "ChatCompletion": ".types",
    "ChatCompletionUsage": ".types",
    "ChatMessage": ".types",
    "ChatMessageRole": ".types",
    "CreateAgentResponse": ".agents",
    "CreateApiKeyResponse": ".api_keys",
    "CreateKnowledgeResponse": ".knowledge",
    "CreateMcpServerResponse": ".mcp_servers",
    "CreateMcpServerToolResponse": ".mcp_servers",
    "DefaultAioHttpClient": "._default_clients",
    "DefaultAsyncHttpxClient": "._default_clients",
    "DeleteAgentResponse": ".agents",
    "DeleteKnowledgeResponse": ".knowledge",
    "DtgAgentSdk": ".client",
    "DtgAgentSdkEnvironment": ".environment",
    "Envelope": ".types",
    "EnvelopeStatus": ".types",
    "GetAgentChannelsResponse": ".agents",
    "GetAgentResponse": ".agents",
    "GetKnowledgeResponse": ".knowledge",
    "GetOrganizationResponse": ".organizations",
    "Knowledge": ".types",
    "KnowledgeContentType": ".types",
    "KnowledgeCreateRequestContentType": ".knowledge",
    "KnowledgeDetail": ".types",
    "ListAgentsResponse": ".agents",
    "ListApiKeysResponse": ".api_keys",
    "ListKnowledgeResponse": ".knowledge",
    "ListMcpServerToolsResponse": ".mcp_servers",
    "ListMcpServersResponse": ".mcp_servers",
    "ListOrganizationMembersResponse": ".organizations",
    "McpServer": ".types",
    "McpServerTool": ".types",
    "McpServerToolAuthType": ".types",
    "McpServerToolKind": ".types",
    "Model": ".types",
    "ModelList": ".types",
    "OkResponse": ".types",
    "Organization": ".types",
    "OrganizationMember": ".types",
    "OrganizationMemberRole": ".types",
    "RevokeApiKeyResponse": ".api_keys",
    "StartAgentResponse": ".agents",
    "StopAgentResponse": ".agents",
    "UpdateAgentChannelsResponse": ".agents",
    "UpdateAgentResponse": ".agents",
    "__version__": ".version",
    "agents": ".agents",
    "api_keys": ".api_keys",
    "gateway": ".gateway",
    "knowledge": ".knowledge",
    "mcp_servers": ".mcp_servers",
    "organizations": ".organizations",
}


def __getattr__(attr_name: str) -> typing.Any:
    module_name = _dynamic_imports.get(attr_name)
    if module_name is None:
        raise AttributeError(f"No {attr_name} found in _dynamic_imports for module name -> {__name__}")
    try:
        module = import_module(module_name, __package__)
        if module_name == f".{attr_name}":
            return module
        else:
            return getattr(module, attr_name)
    except ImportError as e:
        raise ImportError(f"Failed to import {attr_name} from {module_name}: {e}") from e
    except AttributeError as e:
        raise AttributeError(f"Failed to get {attr_name} from {module_name}: {e}") from e


def __dir__():
    lazy_attrs = list(_dynamic_imports.keys())
    return sorted(lazy_attrs)


__all__ = [
    "Agent",
    "AgentStatus",
    "ApiKey",
    "ApiKeyCreateResponse",
    "AsyncDtgAgentSdk",
    "ChannelConfig",
    "ChannelConfigType",
    "ChatCompletion",
    "ChatCompletionUsage",
    "ChatMessage",
    "ChatMessageRole",
    "CreateAgentResponse",
    "CreateApiKeyResponse",
    "CreateKnowledgeResponse",
    "CreateMcpServerResponse",
    "CreateMcpServerToolResponse",
    "DefaultAioHttpClient",
    "DefaultAsyncHttpxClient",
    "DeleteAgentResponse",
    "DeleteKnowledgeResponse",
    "DtgAgentSdk",
    "DtgAgentSdkEnvironment",
    "Envelope",
    "EnvelopeStatus",
    "GetAgentChannelsResponse",
    "GetAgentResponse",
    "GetKnowledgeResponse",
    "GetOrganizationResponse",
    "Knowledge",
    "KnowledgeContentType",
    "KnowledgeCreateRequestContentType",
    "KnowledgeDetail",
    "ListAgentsResponse",
    "ListApiKeysResponse",
    "ListKnowledgeResponse",
    "ListMcpServerToolsResponse",
    "ListMcpServersResponse",
    "ListOrganizationMembersResponse",
    "McpServer",
    "McpServerTool",
    "McpServerToolAuthType",
    "McpServerToolKind",
    "Model",
    "ModelList",
    "OkResponse",
    "Organization",
    "OrganizationMember",
    "OrganizationMemberRole",
    "RevokeApiKeyResponse",
    "StartAgentResponse",
    "StopAgentResponse",
    "UpdateAgentChannelsResponse",
    "UpdateAgentResponse",
    "__version__",
    "agents",
    "api_keys",
    "gateway",
    "knowledge",
    "mcp_servers",
    "organizations",
]
