# This file was auto-generated by Fern from our API Definition.

import typing

CameraCreateRequestVendor = typing.Union[
    typing.Literal["generic_rtsp", "hikvision", "ezviz", "dahua", "onvif_generic", "other"], typing.Any
]
